### ISSUE TITLE
job.progress(x,y) does not seem to be possible from a job running inside a fiber

### ISSUE THREAD

**Issue by LarsBuur** [vsivsi/meteor-job#5] opened 2015-02-02 09:33 UTC
I have several jobs that performs image operations and to simplify things I am using fibers. For some reason I am unable to see the result of a call to e.g. job.progress(33,100) from within the fiber. As soon as the call is moved outside the fiber then the progress is updated accordingly. 

Maybe it is not intended to use a fiber for the jobs?

Best regards,
Lars

**Comment by vsivsi** [comment] 2015-02-05 22:30
Hi @LarsBuur, What you are describing should work fine. Can you point me to a simple Meteor test application that reproduces this issue?

**Comment by LarsBuur** [comment] 2015-02-05 22:31
Sure - thanks for the reply. I will make a small setup.

**Comment by vsivsi** [comment] 2015-02-05 22:33
Just a clarifying question... Are you running in a Fiber on a Meteor Server?  Or in a fiber in a separate node.js process that is not the Meteor environment?  If it's the latter case, then I don't know if it will work, because I haven't tested it.  I'm asking because you reported this issue here (meteor-job) and not in meteor-job-collection.

**Comment by LarsBuur** [comment] 2015-02-05 22:40
My workers are running in a completely separate node.js process. 
The jobs are mostly importing and manipulating data from different sources and some simple image resizing operation. My use of fibers could probably be removed by introducing a series of callbacks.

**Comment by vsivsi** [comment] 2015-02-05 22:42
Hmm. okay. It *should* still work, but I've personally never used fibers outside of Meteor, so I may have made some wrong assumption about that case. And as I said above, I haven't tested this, so there are probably bugs. Example code would be very helpful.  Thanks for clarifying!

**Comment by vsivsi** [comment] 2015-02-06 03:18
Reading up on Fibers a bit and refreshing myself of how meteor-job works internally...

You are probably having trouble because the `ddp` connection that you provide using `Job.setDDP(ddp);` is internally used to make ddp method calls on the server using the `ddp.call()` method, which is asynchronous.

In the Meteor environment, this automatically uses `Meteor.apply()` which is Fiber aware and does the right thing on both server and client.  But in non-Meteor node.js that isn't available, and so I emulate it using the above mentioned `ddp.call()` async method.  However, when you add Fibers into the mix, that async call almost certainly isn't being properly "wrapped" in FIber yielding goodness.

Here's a bit of a hack to try:
```js
// Remove your Job.setDDP(ddp) call and instead do:
wrapped_call = function (ddp_obj) {
   return function(name, params) {
      ddp_obj.call(name, params, function(err, res) {
         if (err) { throw(err); }
         Fiber.current.run(res);
      });
      return Fiber.yield();
   }; 

// "ddp" here is whatever variable you were passing to Job.setDDP()
Job.ddp_apply = wrapped_call(ddp); 
```

If that fixes it, then I should probably change the `Job.setDDP()` mechanism to better accommodate this.

**Comment by vsivsi** [comment] 2015-02-07 01:58
FYI, I changed the code snippet above to define the `fiber` var outside of the ddp callback function

**Comment by vsivsi** [comment] 2015-02-07 10:18
Hi, I've turned the above code into an optional second parameter to the `Job.setDDP()` call.  You can try out the change on the `fiber_support` branch: https://github.com/vsivsi/meteor-job/tree/fiber_support

```js
Fiber = require('fibers');
# Set up ddp connection, etc.
Job.setDDP(ddp, Fiber);
# Run your Job calls with a Fiber... e.g.
try {
   retval = job.progress(x,y);
} catch (err) {
   console.error("Something went wrong!", err);
}
```

Give it a try and let me know what you think...

**Comment by vsivsi** [comment] 2015-02-12 01:22
FYI, I've merged this support into the `dev` branch.  Please give it a try if you can. I'm intending to release it in the next version, but having some help with testing would be great.

**Comment by LarsBuur** [comment] 2015-02-12 07:25
Hi Vaugh - I will give it a try today and report back.

Best regards
Lars

**Comment by LarsBuur** [comment] 2015-02-12 16:06
I am not really sure how this is supposed to work. 

This is what I did:
- clone the --branch dev
- "compile"  using coffee --compile --output lib/ src/

changing my reference 
```
var Job = require("meteor-job");
```
to 
```
var Job = require("./meteor-job/lib/job_class.js');
```
and change 
```
Job.setDDP(ddpClient); 
```
to 
```
Job.setDDP(ddpClient, Fiber);
```

Then I created this method:
```
var tediousFiber = function (job, caller) {
    Fiber(function () {
        var currentJob = 0;
        for (i = 0; i < 100; i++) {
            setTimeout(function () {
                job.progress(currentJob, 100);
                currentJob++;
            }, 100 * i);
        }
        setTimeout(function () {
            job.done();
            caller();
        }, 11 * 1000);
    }).run();
};
```
It could probably be achieved in a prettier fashion ... 

I have also tried multiple different ways of attaching to an existing fiber using 
```
  var fiber = Fiber.current;
```
but then fiber is undefined in all outcomes. 

When I try to execute tediousFiber from within a standalone node runner then this error is thrown:

```
privatepath/meteor-job/lib/job_class.js:468
              return Fiber["yield"]();
                                   ^
Error: yield() called with no fiber running
    at Function.ddp_apply (privatepath/meteor-job/lib/job_class.js:468:36)
    at methodCall (privatepath/meteor-job/lib/job_class.js:24:24)
    at Job.progress (privatepath/meteor-job/lib/job_class.js:944:18)
    at null._onTimeout (privatepath/parseEvents.js:119:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

Should I pass along the fiber - or?

One really strange thing that I am curious about is that when I change 
```
Job.setDDP(ddpClient, Fiber); 
```
back to 
```
Job.setDDP(ddpClient);
```
and leave everything else as it was then the job works and the progress is reported correctly within the Fiber.

**Comment by mitar** [comment] 2015-03-05 05:11
Just skimmed over this ticket, but shouldn't you also make sure you use `Meteor.bindEnvironment`, not just make sure you use the Fiber?

**Comment by vsivsi** [comment] 2015-03-05 05:18
This is for using Fibers outside of Meteor in pure node.js workers.

**Comment by vsivsi** [comment] 2015-03-24 00:11
This has been merged into master

**Closed by vsivsi** 2015-03-24 00:11 UTC
Labels: documentation, enhancement, question
