### ISSUE TITLE
Workers stop collecting ready jobs

### ISSUE THREAD

**Issue by Architecty** [vsivsi/meteor-job#7] opened 2015-12-15 02:57 UTC
I've got an odd error that recently started, and I'm not certain what the issue could be. I have a script that starts a dozen or so workers, each looking for a different job in the same jobCollection. Occasionally a worker will stop accepting new work, even though it's completed its last job and there are more jobs ready / waiting. Other workers will continue pulling their particular job type without complaint. The stopped worker won't pull new work until the script is restarted, at which time it'll continue processing jobs until it either completes the queue or freezes again. 

``` ddp.connect(function(err){
  if(err) throw err;
  ddpLogin(ddp, {
    env: "METEOR_TOKEN",
    method: "account",
    account: config.ddpEmail,
    pass: config.ddpPassword,
    retry: 5,
    plaintext: false
  }, function(err, userInfo){
    if(err) throw err;
    MongoClient.connect(config.mongoURI, function(err, db){
      if(err) throw err;

      var sitesUpdateWorker = Job.processJobs('campusJobs', 'sitesUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(siteListUpdate, job, cb, db);
      });
      var bldgsUpdateWorker = Job.processJobs('campusJobs', 'bldgsUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(BldgListUpdate, job, cb, db);
      });
      var floorsUpdateWorker = Job.processJobs('campusJobs', 'floorsUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(FloorListUpdate, job, cb, db);
      });
      var spacesUpdateWorker = Job.processJobs('campusJobs', 'spacesUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(SpaceListUpdate, job, cb, db);
      });
      var componentsUpdateWorker = Job.processJobs('campusJobs', 'componentsUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(ComponentListUpdate, job, cb, db);
      });
      var fusionUpdateWorker = Job.processJobs('campusJobs', 'fusionUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(FusionUpdate, job, cb, db);
      });
      var scheduleUpdateWorker = Job.processJobs('campusJobs', 'scheduleUpdate', {concurrency:1, workTimeout: 120 * 1000}, function(job, cb){
        XmlRequest(ScheduleUpdate, job, cb, db);
      });
      var documentsUpdateWorker = Job.processJobs('campusJobs', 'documentsUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(DocumentUpdate, job, cb, db);
      });

      var siteValueListWorker = Job.processJobs('campusJobs', 'siteValueListUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        addSiteToQueue(job.data, job.data.siteID, job.data.site_id);
        job.done();
        cb();
      });
      var spaceValueListUpdateWorker = Job.processJobs('campusJobs', 'spaceValueListUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(siteSpaceAttributesUpdate, job, cb, db);
      });
      var bldgValueListUpdateWorker = Job.processJobs('campusJobs', 'bldgValueListUpdate', {concurrency:1, workTimeout: 15 * 1000}, function(job, cb){
        XmlRequest(siteBldgAttributesUpdate, job, cb, db);
      });

    });
  })
})

**Comment by vsivsi** [comment] 2015-12-15 03:53
This is going to be pretty tough to help you with given the lack of any opportunity for me to reproduce this.  I've glanced at your code above and it looks fine.  One thing you can try is to turn on logging on the server-side job-collection so that you can watch the `getWork` requests that are generated by the `processJobs` queues.  It would be interesting to know if the "dead" worker is actually requesting work, or really just gone.

So there are a few ways something like this can happen. You *seem* to imply that the dead worker successfully completes its last job, and then just never gets any more work. It that really true? One thing that will stop a worker cold is if its worker function returns without ever calling the callback.  So is there any way that can ever possibly happen in your `XmlRequest` function? Some exception or other case where `cb()` doesn't get called, but the function returns (or throws and gets caught outside of the worker function?)  A way to test this would be to increase the `concurrency` value to 2, and then see if the idle worker ever starts requesting just one job at a time, never returning to requesting two. And then eventually one of them will stop requesting any jobs because its other slot also didn't call the `cb()`...

It's possible that there's a bug in the `processJobs()` logic, but I highly doubt it, simply because that code has been in place for over a year, hasn't been recently modified, and nobody has reported an error like this before. Virtually everyone who uses jC uses that mechanism, and so I would expect that everyone (or many people at least) would have run into this by now.  So until you can provide a simple reproduction case, I'd assume that somehow you worker has a case where the callback doesn't get invoked.

**Comment by Architecty** [comment] 2015-12-15 04:22
I've gone ahead and set up the logs using the following, `CampusJobs.setLogStream(process.stdout);`, which gives me the following when it's frozen up: 
``` 
I20151214-20:02:29.499(-8)? Mon Dec 14 2015 20:02:29 GMT-0800 (PST), [SERVER], jobReady, params: [[],{"force":false,"time":"2015-12-15T04:02:29.497Z"}]
I20151214-20:02:29.500(-8)? Mon Dec 14 2015 20:02:29 GMT-0800 (PST), [SERVER], jobReady, returned: false
I20151214-20:02:44.501(-8)? Mon Dec 14 2015 20:02:44 GMT-0800 (PST), [SERVER], jobReady, params: [[],{"force":false,"time":"2015-12-15T04:02:44.500Z"}]
I20151214-20:02:44.502(-8)? Mon Dec 14 2015 20:02:44 GMT-0800 (PST), [SERVER], jobReady, returned: false
```
It doesn't look like it's pulling out anything out of the ordinary. 

Looking closer at the jobs that have failed and were put back into the 'ready' queue, it does look like there is a failure in the last job that attempts to process: `Failed for exceeding worker set workTimeout."`. I've just tried extending the workTimeout to accomodate this (from 15s to 60s), but it doesn't look like that solved the issue.

**Comment by vsivsi** [comment] 2015-12-15 04:24
Seems like something in the worker function is hanging for longer than that...  And then never calling the `cb()`!

**Comment by Architecty** [comment] 2015-12-15 04:29
Shouldn't the workTimeout take care of this, even with what appears to be my script dying? I've been relying on it in other cases, where the xml file I'm processing ends up taking longer to be returned than expected, which is what's making this odd.

I'll try setting an internal timeout into the function, and see if that works.

If it's useful, here's the logs of a failed job: 

```
	"log" : [
		{
			"time" : ISODate("2015-12-15T04:16:04.608Z"),
			"runId" : null,
			"level" : "info",
			"message" : "Constructed"
		},
		{
			"time" : ISODate("2015-12-15T04:16:04.609Z"),
			"runId" : null,
			"message" : "Job Submitted",
			"level" : "info"
		},
		{
			"time" : ISODate("2015-12-15T04:16:04.613Z"),
			"runId" : null,
			"message" : "Promoted to ready",
			"level" : "info"
		},
		{
			"time" : ISODate("2015-12-15T04:16:41.362Z"),
			"runId" : "jcWb7c9FKhESt8Z2e",
			"message" : "Job Running",
			"level" : "info"
		},
		{
			"time" : ISODate("2015-12-15T04:17:44.550Z"),
			"runId" : "jcWb7c9FKhESt8Z2e",
			"message" : "Job Failed with Error: Failed for exceeding worker set workTimeout.",
			"level" : "warning"
		},
		{
			"time" : ISODate("2015-12-15T04:17:59.550Z"),
			"runId" : null,
			"message" : "Promoted to ready",
			"level" : "info"
		}
	],
	"workTimeout" : 60000,
	"expiresAfter" : ISODate("2015-12-15T04:17:41.357Z"),
	"failures" : [
		{
			"value" : "Failed for exceeding worker set workTimeout",
			"runId" : "jcWb7c9FKhESt8Z2e"
		}
	]
```

**Comment by Architecty** [comment] 2015-12-15 05:13
Added a `setTimeout` to wait until after the `workTimeout` expires, then check to see if the work was done, and fail itself if it isn't. That seems to be working, but it does seem like it negates the purpose of `workTimeout`.

**Comment by vsivsi** [comment] 2015-12-15 05:13
Hi, no, the workTimeout doesn't do anything to fix the worker side because it is a server-side mechanism. This feature was added to solve the problem of "zombie jobs" on the server. Jobs that are marked as running, but whose workers have died or lost network connectivity.  All processJobs does with this setting is pass it on to the getWork call. It is just the worker's way of telling the server "hey, if you don't hear from me within this amount of time, assume I'm gone and auto-fail the job so some other worker can do it instead".  

But that worker function is like any other node.js function that accepts a callback... If you never call the callback, then whatever was waiting on it will never be notified.

**Comment by vsivsi** [comment] 2015-12-15 05:19
Another possibility that gets you the benefit of both...  Calling job.progress() or job.log() resets the server-side workTimeout for that job.  So your worker can keep its job a live in the case where it hasn't actually died by using that setTimeout to call job.progress(). In the case where he worker has actually gone away, the workerTimeout will still work as intended.

**Comment by Architecty** [comment] 2015-12-15 05:27
Hmm, ok. Just to make sure on something, too -- there's not a way for the job to know on its own if `job.fail()` or `job.done()` has been called, correct? So if I want to make the action of my `setTimeout` dependent on whether or not the job has successfully completed, I need to use my own variables? I'd guessed that checking the _doc.status would let me know, but I see that doesn't seem to be the case.

Also, thanks for being so responsive on this.

**Comment by vsivsi** [comment] 2015-12-15 06:00
You can call job.refresh() and then check the status.

**Comment by vsivsi** [comment] 2015-12-15 06:04
But really, rather than adding a server round-trip, you should probably just keep your own state on that...

**Closed** 2016-01-05 22:44 UTC
Labels: question
